### ISSUE TITLE
您好，在使用中遇到两个问题

### ISSUE THREAD

**Issue by bugstark** [casbin/beego-orm-adapter#1]
```golang
func init() {
	a := beegoormadapter.NewAdapter("mysql", "root:root@tcp(127.0.0.1:3306)/backend")
	e := casbin.NewEnforcer("conf/rbac.conf", a)
	e.LoadPolicy()
	Enforcer=e
}
```
### 问题1:
```shell
must have one register DataBase alias named `default`
```
因为在测试中，没有建立其他model，也没有初始化数据库。
```golang
err = orm.RegisterDataBase("casbin", a.driverName, a.dataSourceName)
```
将casbin改为default即可，或者先从其他地方初始化数据库，

### 问题2:
```shell
<Ormer> table: `.` not found, make sure it was registered with `RegisterModel()`
```
查询得知此问题出在beego orm是需要传入对象指针，此问题尚未解决

**Comment by bugstark** [comment]
### 问题2的原因：
```golang
// LoadPolicy loads policy from database.
func (a *Adapter) LoadPolicy(model model.Model) error {
	var lines []CasbinRule
	err := a.o.Read(&lines)
	if err != nil {
		return err
	}

	for _, line := range lines {
		loadPolicyLine(line, model)
	}

	return nil
}
```
a.o.Read(&lines) 使用了数组指针

**Comment by hsluoyz** [comment]
问题2应该本身不是问题，还是问题1。我其实有点不理解beego orm的RegisterDataBase()，我就是希望能够在数据库不存在的时候创建数据库，然后名字默认为casbin，但也可以指定。你们应该用beego orm比较多了吧，（不然也不会指定用这个，感觉xorm gorm都更好用一些），可以帮我看看哪里写的有问题吗？

**Comment by bugstark** [comment]
你好，我正在研究官方的文档，按照文档，RegisterDataBase()他应该是必须要指定数据库名的，否则会panic
```golang
panic: register db Ping `default`, invalid DSN: missing the slash separating the database name
```
而这个default 我理解的是他是一个 alias ，而beego 默认注册是‘default’

> ORM 必须注册一个别名为 default 的数据库，作为默认使用。--beego官方文档orm部分

**Comment by bugstark** [comment]
之所以不用其他orm的原因是，我们这边使用beego做的restful ，用的beego 提供的bee脚手架生成代码，尽量减少开发时间

**Comment by hsluoyz** [comment]
其实你并没有省开发时间啊，因为adapter也是casbin提供的，是xorm还是gorm还是beego orm对您这边是没有区别的。但是说实话，beego orm目前真的很不完善，我刚才fix了一些问题，但是可能还有问题，我这边目前放弃了，您如果对beego orm很熟，可以帮忙提PR改进这个adapter。或者换用xorm adapter即可，对您那边的改动无非就是加一个库的引用。
