### ISSUE TITLE
adapter support beego2.0

### ISSUE THREAD

**Issue by wpliang** [casbin/beego-orm-adapter#11]
now just support beego1.x, so when I use beego version of 2.x, this adapter cannot work well, I had to modify the source code. so I hope adapter can support beego2.x, thanks.

**Comment by hsluoyz** [comment]
@wpliang please use English to help developers all over the world be able to understand your question :)

**Comment by hsluoyz** [comment]
@closetool plz take a look.

**Comment by hsluoyz** [comment]
@wpliang Beego v2 is supported starting from v3.0.0: https://github.com/casbin/beego-orm-adapter/releases/tag/v3.0.0
