### ISSUE TITLE
Custom database table name

### ISSUE THREAD

**Issue by andrewboxonko** [casbin/beego-orm-adapter#25]
Is it possible to create an adapter and set the custom database table name? (it defaults to casbin_rule)

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
This may help you
https://pkg.go.dev/github.com/beego/beego/v2/client/orm#TableNameI

**Comment by hsluoyz** [comment]
@PokIsemaine how to use it? We should add code example to README
