### ISSUE TITLE
Beego orm DefaultRowsLimit

### ISSUE THREAD

**Issue by memwey** [casbin/beego-orm-adapter#4]
The default amount of returned rows of `All` method is 1000 in beego ORM.

This confusing behavior is described here
https://beego.me/docs/mvc/model/query.md#all

To solve it, change the global variable `DefaultRowsLimit` to -1 to disable this weird limitation

**Comment by hsluoyz** [comment]
Hi @memwey , thanks for pointing it out, can you make a PR about it?

**Comment by memwey** [comment]
@hsluoyz 
I'm not sure if the author of beego will solve it.
In my opinion, it's dangerous to change a global variable. If someone is using this "feature" in his beego website, changing it may cause a big problem.
Maybe write a notice in README.

**Comment by hsluoyz** [comment]
Hi @memwey, the Beego author has merged the PR: https://github.com/astaxie/beego/pull/3625 into develop branch. You can directly use the Beego's develop branch to fix this issue.
